// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import DismissableController from "./dismissable_controller"
application.register("dismissable", DismissableController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import SiteMenuController from "./site_menu_controller"
application.register("site-menu", SiteMenuController)

import { registerControllers } from "@radioactive-labs/plutonium"
registerControllers(application)
